feat: :sparkles: Update

diff --git a/.github/workflows/qapipenile.yml b/.github/workflows/qapipenile.yml
--- a/.github/workflows/qapipenile.yml
+++ b/.github/workflows/qapipenile.yml
@@ -67,3 +67,38 @@ jobs:
     - name: Run new container
       run: |
         ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST }} 'sudo docker run -d -p 8080:80 --name apphtml ${{ secrets.DOCKERHUB_USERNAME }}/apphtml:latest'
+
+    - name: Update system 2
+      run: |
+          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST1 }} << 'EOF'
+          # Update the system
+          sudo yum update -y
+  
+          # Check if Docker is installed
+          if ! command -v docker &> /dev/null
+          then
+            echo "Docker not found, installing..."
+            sudo yum install -y docker
+            sudo systemctl start docker
+            sudo systemctl enable docker
+          else
+            echo "Docker is already installed."
+          fi
+  
+          # Ensure Docker is running
+          sudo systemctl start docker
+          sudo systemctl enable docker
+          EOF
+  
+    - name: Stop running container
+      run: |
+          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST1 }} 'sudo docker stop apphtml || true'
+          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST1 }} 'sudo docker rm apphtml || true'
+  
+    - name: Pull Docker image
+      run: |
+          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST1 }} 'sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/apphtml:latest'
+  
+    - name: Run new container
+      run: |
+          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST1 }} 'sudo docker run -d -p 8080:80 --name apphtml ${{ secrets.DOCKERHUB_USERNAME }}/apphtml:latest'
